# Generated by Django 3.0.6 on 2020-05-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msat', '0002_auto_20200518_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msat',
            name='timestamp',
            field=models.IntegerField(),
        ),
    ]
